ERROR - 2024-04-06 04:15:52 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'auspicious_clus...', 3306, '', 0)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue(Array)
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue(Array)
#5 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2024-04-06 04:15:52 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_users`
WHERE `status` = :status:', [...], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(43): App\Models\CommonModel->getAllValue([...])
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->getData()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\Task\\public\\index.php')
ERROR - 2024-04-06 04:16:09 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'auspicious_clus...', 3306, '', 0)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\Task\app\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\Task\app\Controllers\Home.php(31): App\Models\CommonModel->insertValue(Array)
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->create()
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#3 C:\xampp\htdocs\Task\app\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert(Array)
#4 C:\xampp\htdocs\Task\app\Controllers\Home.php(31): App\Models\CommonModel->insertValue(Array)
#5 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->create()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2024-04-06 04:16:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_users` (`name`, `phone`, `email`) VALUES (:name:, :phone:, :email:)', [...], false)
 3 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\Home.php(31): App\Models\CommonModel->insertValue([...])
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->create()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\Task\\public\\index.php')
ERROR - 2024-04-06 04:16:14 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'auspicious_clus...', 3306, '', 0)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\Task\app\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\Task\app\Controllers\Home.php(31): App\Models\CommonModel->insertValue(Array)
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->create()
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#3 C:\xampp\htdocs\Task\app\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert(Array)
#4 C:\xampp\htdocs\Task\app\Controllers\Home.php(31): App\Models\CommonModel->insertValue(Array)
#5 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->create()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2024-04-06 04:16:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_users` (`name`, `phone`, `email`) VALUES (:name:, :phone:, :email:)', [...], false)
 3 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\Home.php(31): App\Models\CommonModel->insertValue([...])
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->create()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\Task\\public\\index.php')
ERROR - 2024-04-06 04:16:35 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'auspicious_clus...', 3306, '', 0)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\Task\app\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\Task\app\Controllers\Home.php(31): App\Models\CommonModel->insertValue(Array)
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->create()
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#3 C:\xampp\htdocs\Task\app\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert(Array)
#4 C:\xampp\htdocs\Task\app\Controllers\Home.php(31): App\Models\CommonModel->insertValue(Array)
#5 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->create()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2024-04-06 04:16:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_users` (`name`, `phone`, `email`) VALUES (:name:, :phone:, :email:)', [...], false)
 3 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\Home.php(31): App\Models\CommonModel->insertValue([...])
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->create()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\Task\\public\\index.php')
ERROR - 2024-04-06 04:16:40 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'auspicious_clus...', 3306, '', 0)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\Task\app\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\Task\app\Controllers\Home.php(31): App\Models\CommonModel->insertValue(Array)
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->create()
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#3 C:\xampp\htdocs\Task\app\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert(Array)
#4 C:\xampp\htdocs\Task\app\Controllers\Home.php(31): App\Models\CommonModel->insertValue(Array)
#5 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->create()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2024-04-06 04:16:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_users` (`name`, `phone`, `email`) VALUES (:name:, :phone:, :email:)', [...], false)
 3 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\Home.php(31): App\Models\CommonModel->insertValue([...])
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->create()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\Task\\public\\index.php')
ERROR - 2024-04-06 04:17:19 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'auspicious_clus...', 3306, '', 0)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue(Array)
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue(Array)
#5 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2024-04-06 04:17:19 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_users`
WHERE `status` = :status:', [...], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(43): App\Models\CommonModel->getAllValue([...])
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->getData()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\Task\\public\\index.php')
ERROR - 2024-04-06 04:19:02 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'auspicious_clus...', 3306, '', 0)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue(Array)
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue(Array)
#5 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2024-04-06 04:19:02 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_users`
WHERE `status` = :status:', [...], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(43): App\Models\CommonModel->getAllValue([...])
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->getData()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\Task\\public\\index.php')
ERROR - 2024-04-06 04:19:27 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'auspicious_clus...', 3306, '', 0)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue(Array)
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue(Array)
#5 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2024-04-06 04:19:27 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_users`
WHERE `status` = :status:', [...], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(43): App\Models\CommonModel->getAllValue([...])
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->getData()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\Task\\public\\index.php')
ERROR - 2024-04-06 04:20:03 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'auspicious_clus...', 3306, '', 0)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
#5 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2024-04-06 04:20:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_users`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->getData()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\Task\\public\\index.php')
ERROR - 2024-04-06 04:21:23 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'auspicious_clus...', 3306, '', 0)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue(Array)
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue(Array)
#5 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2024-04-06 04:21:23 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_users`
WHERE `status` = :status:', [...], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(43): App\Models\CommonModel->getAllValue([...])
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->getData()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\Task\\public\\index.php')
ERROR - 2024-04-06 04:26:32 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'auspicious_clus...', 3306, '', 0)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Task\app\Models\CommonModel.php(40): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue(Array)
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Task\app\Models\CommonModel.php(40): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue(Array)
#5 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2024-04-06 04:26:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_users`
WHERE `status` = :status:', [...], false)
 3 APPPATH\Models\CommonModel.php(40): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(43): App\Models\CommonModel->getAllValue([...])
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->getData()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\Task\\public\\index.php')
ERROR - 2024-04-06 04:28:08 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'auspicious_clus...', 3306, '', 0)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Task\app\Models\CommonModel.php(40): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue(Array)
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Task\app\Models\CommonModel.php(40): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue(Array)
#5 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2024-04-06 04:28:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_users`
WHERE `status` = :status:', [...], false)
 3 APPPATH\Models\CommonModel.php(40): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(43): App\Models\CommonModel->getAllValue([...])
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->getData()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\Task\\public\\index.php')
ERROR - 2024-04-06 04:28:24 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'auspicious_clus...', 3306, '', 0)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Task\app\Models\CommonModel.php(40): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue(Array)
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Task\app\Models\CommonModel.php(40): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue(Array)
#5 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2024-04-06 04:28:24 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_users`
WHERE `status` = :status:', [...], false)
 3 APPPATH\Models\CommonModel.php(40): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(43): App\Models\CommonModel->getAllValue([...])
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->getData()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\Task\\public\\index.php')
ERROR - 2024-04-06 04:31:18 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'auspicious_clus...', 3306, '', 0)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue(Array)
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue(Array)
#5 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2024-04-06 04:31:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_users`
WHERE `status` = :status:', [...], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(43): App\Models\CommonModel->getAllValue([...])
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->getData()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\Task\\public\\index.php')
ERROR - 2024-04-06 04:33:08 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'auspicious_clus...', 3306, '', 0)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
#5 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2024-04-06 04:33:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_users`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->getData()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\Task\\public\\index.php')
ERROR - 2024-04-06 04:41:03 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'auspicious_clus...', 3306, '', 0)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
#5 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2024-04-06 04:41:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_users`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->getData()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\Task\\public\\index.php')
ERROR - 2024-04-06 04:42:57 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'auspicious_clus...', 3306, '', 0)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
#5 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2024-04-06 04:42:57 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_users`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->getData()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\Task\\public\\index.php')
ERROR - 2024-04-06 04:43:19 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'auspicious_clus...', 3306, '', 0)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
#5 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2024-04-06 04:43:19 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_users`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->getData()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\Task\\public\\index.php')
ERROR - 2024-04-06 04:44:14 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'auspicious_clus...', 3306, '', 0)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
#5 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2024-04-06 04:44:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_users`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->getData()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\Task\\public\\index.php')
ERROR - 2024-04-06 04:48:35 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'auspicious_clus...', 3306, '', 0)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Task\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Task\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Task\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Task\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Task\app\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
#5 C:\xampp\htdocs\Task\system\CodeIgniter.php(943): App\Controllers\Home->getData()
#6 C:\xampp\htdocs\Task\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Task\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Task\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Task\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2024-04-06 04:48:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_users`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(43): App\Models\CommonModel->getAllValue()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->getData()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\Task\\public\\index.php')
